fsSetup

diff --git a/.docker/alpine/usr/local/bin/container-start b/.docker/alpine/usr/local/bin/container-start
--- a/.docker/alpine/usr/local/bin/container-start
+++ b/.docker/alpine/usr/local/bin/container-start
@@ -1,23 +1,34 @@
 #!/bin/sh
 set -e
 
-echo "### CONTAINER START ###";
+forceRun=$1;
 
-if [[ -f "${OS_DATA}/container/start-done" ]]; then
-
-    echo "[OK]";
-
+echo_h1 CONTAINER - START;
+if [[ -f "/run/container/start-done" ]] && [[ "${forceRun}" == '' ]]; then
+    echo "[===]";
 else
-    
-    echo "LOGS - OS";
+    fsSetup_echoHeader h2;
+    fsSetup_clearErrors;
+    # Container
+    fsSetup 777 root root ${ROOT_DATA}/;
+    fsSetup 777 root root ${ROOT_LOGS}/;
+    # OS
+    fsSetup 777 root root ${OS_DATA}/;
+    fsSetup 777 root root ${OS_LOGS}/;
+    # App
+    fsSetup 777 root root ${APP_ROOT}/;
+    # Container
+    #fsSetup 777 root root /run/container/start-done;
+
+    echo_h2 LOGS - OS;
     if [[ ! -e "${OS_LOGS}/logs-link" ]]; then
         ln -s "/var/log" "${OS_LOGS}/logs-link"
         chmod 777 "${OS_LOGS}/logs-link"
     fi
 
-
-    #touch "${OS_DATA}/container/start-done"
-    #chmod 777 "${OS_DATA}/container/start-done"
-    echo "[DONE]"
-
+    echo_h2;
+    if [ $(fsSetup_hasErrors) == '1' ]; then
+        echo "[ERROR]";
+        exit 1;
+    fi
 fi
