MySQL Conf

diff --git a/.docker/sql/usr/local/bin/container-setup b/.docker/sql/usr/local/bin/container-setup
--- a/.docker/sql/usr/local/bin/container-setup
+++ b/.docker/sql/usr/local/bin/container-setup
@@ -6,14 +6,31 @@ echo "### CONTAINER SETUP ###";
 
 
 mysql_check_config() {
-    mysqld --verbose --help
-    local toRun=( "mysqld" "--verbose --help" ) errors
-	if ! errors="$("${toRun[@]}" 2>&1 >/dev/null)"; then
-		echo '!!! ERROR !!!';
-        echo ${errors};
-        #echo $'mysqld failed while attempting to check config\n\tcommand was: '"${toRun[*]}"$'\n\t'"$errors"
-        exit 1;
-	fi
+    #mysqld --verbose --help
+    #local toRun=( "mysqld" "--verbose --help" ) errors
+	#if ! errors="$("${toRun[@]}" 2>&1 >/dev/null)"; then
+	#	echo '!!! ERROR !!!';
+    #    echo ${errors};
+    #    #echo $'mysqld failed while attempting to check config\n\tcommand was: '"${toRun[*]}"$'\n\t'"$errors"
+    #    exit 1;
+	#fi
+
+    chmod 664 /etc/mysql/my.cnf;
+    mysqld --validate-config;
+    
+    error=$?;
+
+    echo "RESULT:${result}";
+    echo "ERROR:${error}";
+
+    #result3="$( mysqld --verbose --help )";
+    #erro3r=$?;
+
+    #echo "RESULT:\n${result3}\n";
+    #echo "ERROR:${error3}";
+
+    #local toRun=( "mysqld" "${--verbose --help}" ) errors2
+    #echo "ERROR:${erros2}";
 }
 
 mysql_get_config() {
@@ -68,7 +85,7 @@ else
 
 
     echo "SQL - CHECK CONFIG";
-    #mysql_check_config
+    mysql_check_config
     
 
     echo "SQL - SOCKET";
